name : SonarCloud Scan
on : 
  push :
    branches : 
      - "master"
      - "main"
      - "feature"
jobs:
  sonarcloud:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: action/checkout@v2
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
